### ISSUE TITLE
Rename to company-eshell-autosuggest

### ISSUE THREAD

**Issue by dakra** [dieggsy/company-eshell-autosuggest#3]
I guess this issue can be closed right away again but I was just surprised that after an update (I use borg) `company-eshell-autosuggest` couldn't be found anymore.

I guess all(?) company backends start with a `company-` prefix so to me the old name makes more sense as it describes the package better.

**Comment by dieggsy** [comment]
@dakra I had this discussion with @purcell earlier. It had been named `company-eshell-autosuggest` because it was not much more than a backend at first. However if you look at the updated README, the recommended method of use is now a minor mode that overrides a few default company settings to use it only for autosuggestions. Because of that change (i.e. it no longer being merely a company backend) I decided the package could have its own standalone name. Sorry for any inconvenience.

**Comment by dakra** [comment]
@dieggsy Ok. It was less about what exactly the package name is but more the rename that unnecessary broke stuff and it's not like the name change was really, really needed.

Anyway, done now and wasn't really a problem, more a minor annoyance I just wanted to let you know ;)

Thanks for the package 👍

**Comment by dieggsy** [comment]
@dakra yeah, sorry about that - I think melpa has a way of designating old package names to avoid that sort of breakage, but I guess borg doesn't use melpa rules so that's sorta irrelevant. And it's true, the package name change was not _necessary_, just preferrable for me :)

Regardless, I didn't mean to sound curt, I'm all for discussing the name of the package if it needs to be discussed or you disagree with my reasoning, though you mentioned that's not really the point. In any case, I'll try to keep borg more in mind for the future.

You're welcome for the package! Suggestions and improvements always welcome!
